import type { Measured, TwinSpec } from "@/lib/twins/types";

function catalog(value: number, unit: Measured["unit"], note: string): Measured {
  return { value, unit, status: "catalog", note };
}

function estimated(value: number, unit: Measured["unit"], range: readonly [number, number], note: string): Measured {
  return { value, unit, status: "estimated", range, note };
}

const approx =
  "Parametric approximation from published catalog dimensions. This is not manufacturer CAD, not a micro-CT scan, and not a radiograph.";

/**
 * Starter twins for the common library systems.
 * Add another object here to extend the atlas. Unknown numbers stay `estimated` with a range.
 * NobelReplace is included as a shape only. It is not one of the 26 library systems, so it cannot name a company.
 */
export const TWINS: readonly TwinSpec[] = [
  {
    id: "megagen-anyridge",
    libraryId: "megagen-anyridge",
    name: "MegaGen AnyRidge",
    source: { title: "MegaGen AnyRidge — KnifeThread", url: "https://imegagen.com/product/1292/" },
    approximation: approx,
    length: estimated(10, "mm", [7, 13], "AnyRidge length series is not quoted on the linked product page as stored here."),
    coronalDiameter: estimated(5, "mm", [4, 8], "Outer thread diameter. The page describes a narrow core with deep blades, not a single diameter."),
    apicalDiameter: estimated(3.2, "mm", [2.4, 4.5], "Apical outer diameter is not quoted. Drawn narrower than the coronal thread."),
    pitch: estimated(1, "mm", [0.8, 1.4], "Pitch is not quoted on the linked page."),
    threadDepth: estimated(1.15, "mm", [0.7, 1.8], "KnifeThread is described as deep relative to the core. The millimetre depth is not quoted."),
    leads: catalog(1, "count", "AnyRidge is the single-lead KnifeThread line in this library, against ST’s double thread."),
    threadProfile: "knife",
    threadNote: "Knife-thin blades. The shape is the catalog description; the millimetre depth is estimated.",
    collar: "none",
    collarHeight: catalog(0, "mm", "Bone-level. No transmucosal collar is described for AnyRidge in this library."),
    apex: "round",
    platformInset: estimated(0.4, "mm", [0, 0.8], "Platform shift is accepted in the library. The inset distance is not quoted."),
    progressive: false,
  },
  {
    id: "megagen-st",
    libraryId: "megagen-st",
    name: "MegaGen ST",
    source: {
      title: "MegaGen ST — 11° internal hex, KnifeThread on a double thread",
      url: "https://imegagen.com/product/22045/",
    },
    approximation: approx,
    length: estimated(10, "mm", [7, 13], "ST length series is not quoted as a single figure on the linked page."),
    coronalDiameter: estimated(4.5, "mm", [3.5, 7], "Outer diameter is not a single quoted figure on the linked page."),
    apicalDiameter: estimated(3.4, "mm", [2.6, 4.5], "Apical diameter is not quoted. Drawn as a milder taper than AnyRidge."),
    pitch: estimated(0.9, "mm", [0.7, 1.3], "Pitch is not quoted. A double lead puts two starts on this pitch."),
    threadDepth: estimated(1, "mm", [0.6, 1.6], "KnifeThread depth is described, not given in millimetres, on the linked page."),
    leads: catalog(2, "count", "The ST page describes KnifeThread added to a double thread."),
    threadProfile: "knife",
    threadNote: "KnifeThread on a double lead. The 11° internal hex is catalog geometry and is inside the body, so this drawing does not show it.",
    collar: "none",
    collarHeight: catalog(0, "mm", "Bone-level on the ST page used by this library."),
    apex: "round",
    platformInset: catalog(0, "mm", "This library reads ST as without a platform switch. That reading is marked interpretation on the system card."),
    progressive: false,
  },
  {
    id: "straumann-tl",
    libraryId: "straumann-tl",
    name: "Straumann Tissue Level",
    source: {
      title: "Straumann Tissue Level product information",
      url: "https://www.straumann.com/content/dam/media-center/straumann/en/documents/brochure/product-information/490.269-en_low.pdf",
    },
    approximation: approx,
    length: estimated(10, "mm", [8, 14], "Endosteal lengths in the tissue-level family. This twin uses 10 mm."),
    coronalDiameter: estimated(4.1, "mm", [3.3, 4.8], "Regular and wide neck diameters in the tissue-level family. This twin uses 4.1 mm."),
    apicalDiameter: estimated(3.9, "mm", [3.3, 4.8], "The threaded body is drawn parallel. A small apical difference is estimated."),
    pitch: estimated(0.8, "mm", [0.6, 1.2], "Thread pitch is not quoted in the library entry for this brochure."),
    threadDepth: estimated(0.35, "mm", [0.2, 0.6], "Thread depth is not quoted. Drawn as a standard V, not a knife blade."),
    leads: catalog(1, "count", "This library accepts a single lead for Tissue Level."),
    threadProfile: "v",
    threadNote: "Standard thread below the machined collar.",
    collar: "tulip",
    collarHeight: catalog(2.8, "mm", "Standard neck 2.8 mm, as stated on the Tissue Level card from the brochure. Standard Plus is 1.8 mm and is a different neck."),
    apex: "round",
    platformInset: catalog(0, "mm", "The flare is the collar. There is no separate platform-switch inset in this drawing."),
    progressive: false,
  },
  {
    id: "straumann-bl",
    libraryId: "straumann-bl",
    name: "Straumann Bone Level",
    source: {
      title: "Straumann Bone Level prosthetic procedures",
      url: "https://www.straumann.com/content/dam/media-center/straumann/en/documents/brochure/technical-information/702061-en_low.pdf",
    },
    approximation: approx,
    length: estimated(10, "mm", [8, 14], "Bone Level lengths. This twin uses 10 mm."),
    coronalDiameter: estimated(4.1, "mm", [3.3, 4.8], "Bone Level diameters. This twin uses 4.1 mm."),
    apicalDiameter: estimated(3.6, "mm", [3.3, 4.8], "BL is parallel and BLT adds an apical taper. This drawing uses a small apical taper so one twin covers the family."),
    pitch: estimated(0.8, "mm", [0.6, 1.2], "Pitch is not quoted in the library entry."),
    threadDepth: estimated(0.35, "mm", [0.2, 0.55], "Thread depth is not quoted."),
    leads: catalog(1, "count", "This library accepts a single lead for Bone Level."),
    threadProfile: "v",
    threadNote: "Standard thread. CrossFit is internal and is not drawn.",
    collar: "none",
    collarHeight: catalog(0, "mm", "Bone-level. No transmucosal collar."),
    apex: "round",
    platformInset: estimated(0.35, "mm", [0.2, 0.6], "Platform shift is accepted in the library. The inset is not a quoted millimetre."),
    progressive: false,
  },
  {
    id: "nobel-active",
    libraryId: "nobel-active",
    name: "NobelActive",
    source: { title: "NobelActive product page", url: "https://www.nobelbiocare.com/en-int/nobelactive" },
    approximation: approx,
    length: estimated(11.5, "mm", [8.5, 15], "NobelActive length series. 11.5 mm is a common mid length, not a single quoted figure in this repo."),
    coronalDiameter: estimated(4.3, "mm", [3.5, 5], "NP/RP/WP diameters. This twin uses 4.3 mm."),
    apicalDiameter: estimated(2.2, "mm", [1.5, 3], "Strong taper to a point. The apical diameter is estimated."),
    pitch: estimated(1.2, "mm", [0.8, 1.8], "Widely spaced threads are described. Pitch is not quoted here."),
    threadDepth: estimated(0.55, "mm", [0.35, 0.9], "Aggressive thread. Depth is not quoted."),
    leads: catalog(2, "count", "This library scores NobelActive as a double lead."),
    threadProfile: "v",
    threadNote: "Coarse double-lead thread on a strong taper. The internal cone is not drawn.",
    collar: "none",
    collarHeight: catalog(0, "mm", "Bone-level."),
    apex: "point",
    platformInset: estimated(0.4, "mm", [0.2, 0.7], "Platform shift is accepted. The inset is estimated."),
    progressive: false,
  },
  {
    id: "nobel-parallel",
    libraryId: "nobel-parallel",
    name: "NobelParallel CC",
    source: {
      title: "Materials (2022): NobelParallel described with a 12° conical connection",
      url: "https://www.mdpi.com/1996-1944/15/2/511",
    },
    approximation: approx,
    length: estimated(10, "mm", [7, 15], "Length series is not a single figure in the cited paper."),
    coronalDiameter: estimated(4.3, "mm", [3.75, 5], "Typical NobelParallel diameters. This twin uses 4.3 mm."),
    apicalDiameter: estimated(4.1, "mm", [3.75, 5], "Parallel body. A small difference is estimated."),
    pitch: estimated(0.8, "mm", [0.6, 1.2], "Pitch is not quoted in the cited paper."),
    threadDepth: estimated(0.35, "mm", [0.2, 0.55], "Thread depth is not quoted."),
    leads: catalog(1, "count", "This library accepts a single lead for NobelParallel CC."),
    threadProfile: "v",
    threadNote: "Standard thread on a parallel body. The 12° cone is internal and is not drawn.",
    collar: "none",
    collarHeight: catalog(0, "mm", "Bone-level."),
    apex: "round",
    platformInset: estimated(0.35, "mm", [0.2, 0.6], "The cited paper notes built-in platform shift. The inset distance is estimated."),
    progressive: false,
  },
  {
    id: "nobel-replace",
    libraryId: null,
    name: "NobelReplace (not in this library)",
    source: { title: "Nobel Biocare", url: "https://www.nobelbiocare.com/en-int/nobelreplace-cc" },
    approximation:
      "NobelReplace is not one of the 26 systems this bench ranks. The drawing is a tapered stand-in so a sample can be rendered. It does not add a company to the short list.",
    length: estimated(10, "mm", [8, 16], "Replace length series. Estimated."),
    coronalDiameter: estimated(4.3, "mm", [3.5, 5], "Replace diameters. Estimated."),
    apicalDiameter: estimated(2.8, "mm", [2, 3.5], "Tapered body. Apical diameter estimated."),
    pitch: estimated(0.9, "mm", [0.6, 1.4], "Pitch is not quoted here."),
    threadDepth: estimated(0.4, "mm", [0.25, 0.7], "Thread depth is not quoted here."),
    leads: estimated(1, "count", [1, 2], "Lead count is not taken from a page stored in this repo."),
    threadProfile: "v",
    threadNote: "Estimated V thread. Not used to name a company.",
    collar: "none",
    collarHeight: estimated(0, "mm", [0, 0.5], "Bone-level assumption."),
    apex: "round",
    platformInset: estimated(0.3, "mm", [0, 0.6], "Inset estimated."),
    progressive: false,
  },
  {
    id: "osstem-tsiii",
    libraryId: "osstem-tsiii",
    name: "Osstem TS III",
    source: { title: "Osstem implant systems", url: "https://en.osstem.com/" },
    approximation: approx,
    length: estimated(10, "mm", [7, 13], "Length series is not a single figure on the linked home page."),
    coronalDiameter: estimated(4.5, "mm", [3.5, 5], "Diameter series estimated."),
    apicalDiameter: estimated(3.3, "mm", [2.5, 4], "Mild taper. Apical diameter estimated."),
    pitch: estimated(0.8, "mm", [0.6, 1.2], "Pitch is not quoted on the linked page."),
    threadDepth: estimated(0.4, "mm", [0.25, 0.6], "Thread depth is not quoted."),
    leads: estimated(2, "count", [1, 2], "Many TS III fixtures are described as double lead. Not every SKU is."),
    threadProfile: "v",
    threadNote: "Standard thread. Hiossen ET III is the radiographic twin and is not a second drawing.",
    collar: "none",
    collarHeight: catalog(0, "mm", "Bone-level in this library."),
    apex: "cutting",
    platformInset: estimated(0.3, "mm", [0, 0.6], "Platform shift is accepted. Inset estimated."),
    progressive: false,
  },
  {
    id: "dentium-superline",
    libraryId: "dentium-superline",
    name: "Dentium SuperLine",
    source: {
      title: "Dentium SuperLine II",
      url: "https://www.dentiumusa.com/products/implant-systems/superline-2",
    },
    approximation: approx,
    length: estimated(10, "mm", [7, 14], "Length series estimated from the product family, not a single quoted figure stored here."),
    coronalDiameter: estimated(4.5, "mm", [3.6, 7], "Diameter series estimated."),
    apicalDiameter: estimated(2.6, "mm", [2, 3.5], "Tapered body. Apical diameter estimated."),
    pitch: estimated(1, "mm", [0.7, 1.4], "Pitch is not quoted on the linked page as stored here."),
    threadDepth: estimated(0.5, "mm", [0.3, 0.8], "Thread depth is not quoted."),
    leads: catalog(2, "count", "Dentium describes SuperLine II as double-threaded."),
    threadProfile: "v",
    threadNote: "Double-lead thread on a taper. The internal hex index is not drawn.",
    collar: "none",
    collarHeight: catalog(0, "mm", "No microthread collar, unlike Implantium, in this library."),
    apex: "cutting",
    platformInset: estimated(0.35, "mm", [0.2, 0.6], "Platform shift is accepted. Inset estimated."),
    progressive: false,
  },
  {
    id: "neodent-helix",
    libraryId: "neodent-helix",
    name: "Neodent Helix GM",
    source: {
      title: "Neodent GM manual",
      url: "https://www.straumann.com/content/dam/media-center/neodent/en/documents/manual/10129_neodent_gm_manual_en_eU_lr-prosthetics.pdf",
    },
    approximation: approx,
    length: estimated(10, "mm", [8, 16], "Helix length series. This twin uses 10 mm."),
    coronalDiameter: estimated(4.3, "mm", [3.5, 5], "Helix diameters. This twin uses 4.3 mm."),
    apicalDiameter: estimated(2.4, "mm", [1.8, 3.2], "Strong taper. Apical diameter estimated."),
    pitch: estimated(1.1, "mm", [0.8, 1.6], "Pitch is not quoted in the library summary of the GM manual."),
    threadDepth: estimated(0.55, "mm", [0.35, 0.85], "Aggressive thread. Depth estimated."),
    leads: catalog(2, "count", "This library scores Helix GM as a double lead."),
    threadProfile: "v",
    threadNote: "Coarse double-lead thread. The 16° Grand Morse cone is catalog geometry and is internal, so it is not drawn.",
    collar: "none",
    collarHeight: catalog(0, "mm", "Bone-level."),
    apex: "cutting",
    platformInset: estimated(0.4, "mm", [0.2, 0.7], "Platform shift is accepted. Inset estimated."),
    progressive: false,
  },
  {
    id: "zimmer-tsv",
    libraryId: "zimmer-tsv",
    name: "Zimmer Tapered Screw-Vent",
    source: {
      title: "FDA K133339 Tapered Screw-Vent triple-lead description",
      url: "https://www.accessdata.fda.gov/cdrh_docs/pdf13/K133339.pdf",
    },
    approximation: approx,
    length: estimated(10, "mm", [8, 16], "TSV length series. This twin uses 10 mm."),
    coronalDiameter: estimated(4.7, "mm", [3.7, 6], "TSV diameters. This twin uses 4.7 mm."),
    apicalDiameter: estimated(3.4, "mm", [2.5, 4.2], "Apical taper. Diameter estimated."),
    pitch: estimated(0.6, "mm", [0.45, 0.9], "Triple lead makes the apparent pitch shorter. The filing describes the lead, not this millimetre pitch."),
    threadDepth: estimated(0.4, "mm", [0.25, 0.6], "Thread depth is not the quoted figure in the library summary."),
    leads: catalog(3, "count", "FDA K133339 documents an external triple-lead thread."),
    threadProfile: "v",
    threadNote: "Triple-lead thread. The 1.5 mm internal hex is catalog geometry and is not drawn on the outside.",
    collar: "machined",
    collarHeight: estimated(0.8, "mm", [0, 1.5], "Machined-collar and textured-to-the-top versions both exist. This twin draws a short machined band."),
    apex: "cutting",
    platformInset: estimated(0, "mm", [0, 0.4], "Platform switch is not required by the library entry."),
    progressive: false,
  },
  {
    id: "biohorizons-ti",
    libraryId: "biohorizons-ti",
    name: "BioHorizons Tapered Internal",
    source: { title: "BioHorizons Tapered Internal", url: "https://www.biohorizons.com/Products/Tapered" },
    approximation: approx,
    length: estimated(10.5, "mm", [7.5, 15], "Tapered Internal lengths. This twin uses 10.5 mm."),
    coronalDiameter: estimated(4.6, "mm", [3.8, 5.8], "Diameter series estimated."),
    apicalDiameter: estimated(3.3, "mm", [2.4, 4.2], "Taper. Apical diameter estimated."),
    pitch: estimated(0.9, "mm", [0.6, 1.3], "Pitch is not quoted on the linked page as stored here."),
    threadDepth: estimated(0.45, "mm", [0.3, 0.7], "Buttress depth is not quoted."),
    leads: catalog(1, "count", "This library accepts a single lead for Tapered Internal."),
    threadProfile: "reverse-buttress",
    threadNote: "Reverse buttress, as the product is described in this library. Laser-Lok is a surface and is not a radiographic collar in this drawing.",
    collar: "none",
    collarHeight: catalog(0, "mm", "Bone-level body. Laser-Lok is not drawn as a separate neck."),
    apex: "cutting",
    platformInset: catalog(0, "mm", "This library does not require a platform switch for Tapered Internal."),
    progressive: false,
  },
  {
    id: "ankylos",
    libraryId: "ankylos",
    name: "Ankylos C/X",
    source: {
      title: "Ankylos surgical manual",
      url: "https://www.dentsplysirona.com/content/dam/master/product-procedure-brand-categories/implant-dentistry/collateral-marketing-product/ankylos/document/brochure/32671086-ankylos-surgical-manual/IMP-Brochure-Ankylos-Surgical-Manual_32671086-USX-2206_LR.pdf",
    },
    approximation: approx,
    length: estimated(11, "mm", [8, 14], "Ankylos lengths. This twin uses 11 mm."),
    coronalDiameter: estimated(4.5, "mm", [3.5, 5.5], "Diameter series estimated."),
    apicalDiameter: estimated(3.6, "mm", [2.8, 4.5], "Mild taper. Apical diameter estimated."),
    pitch: estimated(0.85, "mm", [0.6, 1.2], "Pitch is not a single quoted figure in the library summary of the manual."),
    threadDepth: estimated(0.45, "mm", [0.2, 0.8], "Depth at mid-body. The manual’s progressive thread is the catalog fact; the millimetres are estimated."),
    leads: catalog(1, "count", "This library accepts a single lead for Ankylos."),
    threadProfile: "buttress",
    threadNote: "Progressive thread: depth increases toward the apex, as the surgical manual describes. TissueCare is internal and is not drawn.",
    collar: "none",
    collarHeight: catalog(0, "mm", "No polished transmucosal collar."),
    apex: "round",
    platformInset: estimated(0.3, "mm", [0, 0.6], "The prosthetic seat sits at or slightly below the crest. The drawn inset is estimated."),
    progressive: true,
  },
];

export function getTwin(id: string): TwinSpec | undefined {
  return TWINS.find((twin) => twin.id === id);
}

export function libraryTwins(): TwinSpec[] {
  return TWINS.filter((twin) => twin.libraryId);
}
